### PR TITLE
Added autoregister all user defined functions

### PR DESCRIPTION
**Pull request by REJack**
Doesn't works with CamelCase functions.

@waptik Test this please, if it works I'll add this PR to the next Version.

### CODE REVIEW

**Comment by waptik** [comment]
It doesn't work at my end either. Neither does any function under $func_name. This is what I have been facing for two weeks now and it seems no one can help
I also got this error : get_defined_functions() expects exactly 0 parameters, 1 given
So I just let get_defined_functions() be without parameter.

**Comment by REJack** [comment]
Which version of PHP do you use v5.6 or v7?

**Comment by REJack** [comment]
Try it now again please, I removed the parameter, it works only for 7.0.15+/7.1.1+ 😅

**Comment by waptik** [comment]
I'm using V5.6 on Android 4.2.2 for local development. I'll let you know by week ending when I try it on my live website.
So should I try it on php7?  I can do that on my shared hosting.
Update: I was able to access my shared hosting account and changed php version from 5.6 to 7.0 but still not working. As you can see in the attached file, it's a screenshot of the portion which this pull contains. Also I commented the loop on functions that belongs to twiggy config file to see if any url helper would work
screenshot_2017-09-01-01-41-25
Also in the next picture you can see the output of the error. 
screenshot_2017-09-01-01-48-06

**Comment by waptik** [comment]
So should I try it on php7?  I can do that on my shared hosting

**Comment by REJack** [comment]
If you get still function not found errors with the auto register, check if your helpers (url) are loaded.

**Comment by waptik** [comment]
Yeah sure I loaded the url helper. If I comment the loop of $func_name and uncomment the loop of $function inside Twig library, everything works out perfectly with the functions inside twiggy config file.
BTW if this can help,  I use twig v1.31.0 as I'm unable to use composer at the moment in order to use the latest version. 
screenshot_2017-09-01-12-29-24
screenshot_2017-09-01-12-27-53

**Comment by REJack** [comment]
I don't know it right but, try to switch the line 11 with line 15 in your controller. Maybe twiggy doesn't register functions they loaded after twiggy itself. 

I tried it only with autoloaded helpers 😅

**Comment by REJack** [comment]
What's your problems with Composer.

A small tutorial for composer usage: 
1. install twig in `application` over composer (`composer require twig/twig:~1.0`)
2. change `$config['composer_autoload'] = FALSE;` to `$config['composer_autoload'] = TRUE;` in `application/config/config.php` (Line 139 in CI3.1.5)
3. change `$config['twiggy']['load_twig_engine']` to `false` in `application/config/twiggy.php` (Line 133 in Twiggy v0.9.6)

Twiggy works at the moment only with Twig __v1.X__

**Comment by waptik** [comment]
I know how itworks. I can't use it because I'm PC-less atm.  I'm doing everything on my Samsung galaxy s3 mini for now.

**Comment by waptik** [comment]
So now I was able to make it work. I autoloaded my libraries and helpers directly from the autoload file instead of my MY_Controller to avoid any misunderstanding of which file should be loaded first, thanks for the suggestion. 
Looks like camelcase works great at my end. See in the attached files. 
screenshot_2017-09-01-18-09-50
screenshot_2017-09-01-18-09-42

**Comment by REJack** [comment]
Sweet, I'll push this PR in the next days.

PHP Developing on an Android, oh my god way to less screen 😄 I need at least 1920x1080 😀

How you mean that camelcase works? I mean'd any functions name thats written in CamelCase like getById that's doesn't work, this issue is related to PHP's get_defined_functions() function it returns any function name lower-cased :/

**Comment by waptik** [comment]
Well I don't have choice as of now so I have to do some coding into my little side project. 
Yeah you are right about the camelCase functions issue, I tested it and I was asked if I wasn't looking for the lowercase of the function in question. At least that's the only bug for now. Here are some suggestions I'll recommend you do before merging this pull. 
1- add a line in twiggy config file as follows:
```php
/* Using all user defined functions
* if set to TRUE make sure you don't have camelCase functions
* ex : having like  function setId(){}  will result in changing its usage inside
* twig as {{ setid() }} because PHP's get_defined_functions() function returns any function name lower-cased.
* By default it is being set to FALSE
*/
$config['twiggy']['use_user_defined_functions] = FALSE;
```

2- inside Twiggy.php library file add the following condition before line 94 of this pull as follows:
`if($this->_config['twiggy']['use_user_defined_functions] == TRUE){
....
}`
I hope you get my point.

**Comment by REJack** [comment]
Done 😄 the config option was on my list too. 

I'll merge it in the next days.

**Comment by waptik** [comment]
Hahaha you had in mind but I spilt it out first:stuck_out_tongue_winking_eye:
Thanks for this and everything. 
This is my first public contribution to open source. Usually I add features to tools I use and keep it to myself. 
When I got hold of my pc, I'll try to ask for pulls of my modifications in this library cos I did a lot to suit my needs and maybe it might help others too. 
I look forward to the seeing the merge happen and the release of v1

**Pull request merged**
